import type { Metadata } from 'next';

import { getGlobalData } from '@/api/api-server';
import Header from '@/components/_layout/Header';
import Footer from '@/components/_layout/Footer';
import Providers from '@/context/Providers';

import '@/styles/main.scss';
import { BACKEND_URL, FRONTEND_URL, SITE_TITLE } from '@/CONSTANTS';
import { Media } from '@backend-types/media';
import { SharedSeo } from '@backend-types/sharedSeo';
import { notFound } from 'next/navigation';

import NextTopLoader from 'nextjs-toploader';
import ReloadToTop from '@/components/_layout/ReloadToTop';
import { getServerSession } from 'next-auth';
import { authConfig } from '@/configs/auth';

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export async function generateMetadata(): Promise<Metadata> {
	const { globalData } = await getGlobalData();

	const pageTitle = globalData.seo?.metaTitle || globalData.seo?.ogTitle || SITE_TITLE;
	const seo: SharedSeo = globalData?.seo || {};

	const {
		canonicalUrl,
		metaDescription,
		keywords,
		metaTitle,
		metaRobots,
		preventIndexing,
		metaViewport,
		ogTitle,
		ogDescription,
		ogImage,
		ogUrl,
		ogType,
		twitterCard,
		twitterTitle,
		twitterDescription,
		twitterImage,
	} = seo;

	// Логика разбора metaRobots или флага preventIndexing
	const isNoIndex = preventIndexing || metaRobots?.includes('noindex');
	const isNoFollow = metaRobots?.includes('nofollow');

	// Формирование URL для OpenGraph и Twitter изображений
	const resolveImageUrl = (image?: Media | null) => {
		if (!image?.url) return '/images/logo.png';
		return image.url.startsWith('http') ? image.url : `${BACKEND_URL}${image.url}`;
	};

	const ogImageUrl = resolveImageUrl(ogImage);
	const twitterImageUrl = resolveImageUrl(twitterImage || ogImage);

	return {
		metadataBase: new URL(FRONTEND_URL),
		title: pageTitle,
		description: metaDescription,
		keywords: keywords,
		// viewport: metaViewport,
		icons: {
			icon: '/images/favicon.png',
		},
		alternates: {
			canonical: canonicalUrl || FRONTEND_URL,
		},
		robots: {
			index: !isNoIndex,
			follow: !isNoFollow,
		},
		openGraph: {
			title: ogTitle || pageTitle,
			description: ogDescription || metaDescription,
			url: ogUrl || canonicalUrl || FRONTEND_URL,
			siteName: pageTitle,
			// eslint-disable-next-line
			type: (ogType as any) || 'website',
			locale: 'en_EN',
			images: [
				{
					url: ogImageUrl,
					width: ogImage?.width || 1200,
					height: ogImage?.height || 630,
					alt: ogImage?.alternativeText || pageTitle,
				},
			],
		},
		twitter: {
			card: twitterCard || 'summary_large_image',
			title: twitterTitle || pageTitle,
			description: twitterDescription || ogDescription || metaDescription,
			images: [twitterImageUrl],
		},
	};
}

export default async function RootLayout({ children }: LayoutProps<'/'>) {
	const { globalData, menuPrimary, menuFooter } = await getGlobalData();
	const global = { globalData, menuPrimary, menuFooter };
	const providerTwoData = 'Hello provider';

	// В App Router передача authConfig обязательна для получения правильного JWT/Session
	// В статических страницах работает неккоректно
	// Ломает статическую генерацию страниц по слагам если вызывать в layout
	// const session = await getServerSession(authConfig);

	// console.log('globalData', globalData);
	// console.log('menuPrimary', menuPrimary);
	// console.log('menuFooter', menuFooter);

	return (
		<html lang="en" data-scroll-behavior="smooth" data-theme="dark-">
			<body>
				{/* <ReloadToTop /> */}
				<NextTopLoader
					color="orange"
					initialPosition={0.08}
					crawlSpeed={200}
					height={5}
					crawl={true}
					showSpinner={false}
					easing="ease"
					speed={200}
					shadow="0 0 10px orange,0 0 5px orange"
					// template='<div class="bar" role="bar"><div class="peg"></div></div>
					// <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
					zIndex={1600}
					showAtBottom={false}
				/>

				<Providers data={{ global, providerTwoData }}>
					<Header data={{ globalData, menuPrimary }} />
					{children}
					<Footer data={{ globalData, menuPrimary, menuFooter }} />
				</Providers>
			</body>
		</html>
	);
}
