import type { Metadata } from 'next';

import '@/styles/main.scss';
import { getGlobalData } from '@/api/api-server';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import Providers from '@/context/Providers';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: LayoutProps<'/'>) {
	const { globalData, menuPrimary, menuFooter } = await getGlobalData();
	// console.log('globalData', globalData);
	// console.log('menuPrimary', menuPrimary);
	// console.log('menuFooter', menuFooter);

	return (
		<html lang="en">
			<body>
				<Providers data={{ globalData, menuPrimary, menuFooter }}>
					<Header data={{ globalData, menuPrimary }} />
					<main id="main-content">{children}</main>
					<Footer data={{ globalData, menuPrimary, menuFooter }} />
				</Providers>
			</body>
		</html>
	);
}
