import { Media } from './media';
import { ProductsProductVariations } from './productsProductVariations';
import { ProductCategory } from './productCategory';
import { SharedSeo } from './sharedSeo';

export interface Product {
  id?: number;
  documentId?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  publishedAt?: Date | string;
  locale?: string | null;
  title: string;
  slug?: string;
  sku?: string;
  groupId?: string;
  price: number;
  priceOld?: number;
  stockStatus?: "inStock" | "outOffStock";
  description?: any;
  attributes?: any;
  images?: Media[] | null;
  overview?: string;
  deliveryNotice?: string;
  badge?: any;
  variations?: ProductsProductVariations[] | null;
  product_category?: ProductCategory | null;
  sections?: any;
  seo?: SharedSeo | null;
};
